#!/usr/bin/env bash
# setup_guard.sh — Bake release keystore fingerprint into cert_hash.h
#
# Usage:
#   cd android
#   bash scripts/setup_guard.sh <keystore.jks> <alias>
#
# Example:
#   bash scripts/setup_guard.sh release.jks iwx
#
# After running this script, rebuild APK:
#   ./gradlew assembleRelease
#
# Any repackaged/re-signed APK will FREEZE and die.

set -e

KEYSTORE="${1:?Usage: $0 <keystore.jks> <alias>}"
ALIAS="${2:?Usage: $0 <keystore.jks> <alias>}"
CERT_H="$(dirname "$0")/../app/src/main/cpp/cert_hash.h"

echo "🔑  Keystore : $KEYSTORE  (alias: $ALIAS)"
echo "    Enter keystore password when prompted."

TMP=$(mktemp /tmp/cert_XXXXXX.der)
keytool -exportcert -keystore "$KEYSTORE" -alias "$ALIAS" -file "$TMP" 2>/dev/null || \
keytool -exportcert -keystore "$KEYSTORE" -alias "$ALIAS" -file "$TMP"

SHA256=$(openssl dgst -sha256 -binary "$TMP" | xxd -p | tr -d '\n')
rm -f "$TMP"
echo "📋  SHA-256 : $SHA256"

XK=(0x4B 0x7A 0x39 0x21 0x6D 0x56 0x23 0x72 0x58 0x77 0x32 0x24)
ENC=""
for i in $(seq 0 31); do
    B=$((16#${SHA256:$((i*2)):2}))
    K=$((${XK[$((i % 12))]}))
    V=$(( B ^ K ))
    ENC+="$V"
    [ $i -lt 31 ] && ENC+=", "
    [ $(( (i+1) % 8 )) -eq 0 ] && ENC+="\n    "
done

cat > "$CERT_H" << HEREDOC
// cert_hash.h — AUTO-GENERATED by setup_guard.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
// Keystore: $KEYSTORE  alias: $ALIAS
// DO NOT edit manually.
#pragma once
static const unsigned char _xk[] = {0x4B,0x7A,0x39,0x21,0x6D,0x56,0x23,0x72,0x58,0x77,0x32,0x24};
static const int _ce[32] = {
    $(echo -e "$ENC")
};
static const int _pe[]  = {40,21,84,15,12,56,71,0,55,30,86,10,38,21,93,76,3,51,80,19};
static const int _pe_len = 20;
#define CERT_HASH_CONFIGURED 1
HEREDOC

echo ""
echo "✅  cert_hash.h updated → $CERT_H"
echo "🔒  Protection ACTIVE — rebuild APK to apply."
