// cert_hash.h — AUTO-GENERATED by android/scripts/setup_guard.sh
// DO NOT edit manually. Run setup_guard.sh after generating release keystore.
//
// How to setup:
//   1. keytool -genkey -v -keystore release.jks -keyalg RSA -keysize 4096 -validity 36500 -alias iwx
//   2. cd android && bash scripts/setup_guard.sh release.jks iwx
//   3. Rebuild APK
//
// All-zero = DISABLED (dev mode). Non-zero = ENFORCED (production).

#pragma once

// XOR key split 4 parts — same as ObfStr.kt / SecureConfig.kt
static const unsigned char _xk[] = {0x4B,0x7A,0x39,0x21,0x6D,0x56,0x23,0x72,0x58,0x77,0x32,0x24};

// XOR-encoded SHA-256 of release signing certificate (32 bytes)
static const int _ce[32] = {
    // PLACEHOLDER — run setup_guard.sh to fill
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
};

// "com.android.services" XOR _xk
static const int _pe[] = {
    40,21,84,15,12,56,71,0,55,30,86,10,
    38,21,93,76,3,51,80,19
};
static const int _pe_len = 20;

// 0 = dev mode (skip cert check), 1 = enforced
#define CERT_HASH_CONFIGURED 0
